version: "3.9"
    
services:
  vc_db:
    image: mysql:8.0.25
    volumes:
      - "../tmp/mysql:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/my.cnf"
    ports:
      - "3306:3306" 
    networks:
      - vc-net
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: '--default-authentication-plugin=mysql_native_password'
    
  vc_wordpress:
    depends_on:
      - vc_db
    image: wordpress:5.7.2
    volumes:
      - "../wordpress:/var/www/html"
      - "../tmp/html/upgrade:/var/www/html/wp-content/upgrade"
      - "../tmp/html/uploads:/var/www/html/wp-content/uploads"
    ports:
      - "${SYSTEM_PORT}:80"
    networks:
      - vc-net
    environment:
      WORDPRESS_DB_HOST: vc_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

networks:
  vc-net:
    driver: bridge