version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:5.7.2
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "${SYSTEM_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: piemontez
      WORDPRESS_DB_PASSWORD: 0rq9@Ntl
      WORDPRESS_DB_NAME: 0rq19@Ntl
volumes:
  db_data: {}
  wordpress_data: {}